### ISSUE TITLE
issue with download

### ISSUE THREAD

**Issue by bgf2** [developeranaz/Mega.nz-Rclone-Index-Heroku-BETA#1]
getting this in logs 

2021-07-17T07:22:55.074083+00:00 app[web.1]: 2021/07/17 07:22:55 ERROR : file.rar: ReadFileHandle.Read error: low level retry 6/10: Http Status: 509 Bandwidth Limit Exceeded

**Comment by developeranaz** [comment]
> getting this in logs
> 
> 2021-07-17T07:22:55.074083+00:00 app[web.1]: 2021/07/17 07:22:55 ERROR : file.rar: ReadFileHandle.Read error: low level retry 6/10: Http Status: 509 Bandwidth Limit Exceeded
Hi , @bgf2  don't deploy Beta Project its maybe unstable/incomplete.
Deploy this https://github.com/developeranaz/Mega.nz-Rclone-Index-Heroku
