### ISSUE TITLE
Application error

### ISSUE THREAD

**Issue by mikeje** [developeranaz/Mega.nz-Rclone-Index-Heroku-BETA#2]
After deploying and opening the app, it shows "Application error
An error occurred in the application and your page could not be served. If you are the application owner, check your logs for details. You can do this from the Heroku CLI with the command
heroku logs --tail'"

![image](https://user-images.githubusercontent.com/87743297/126441421-1a35ec92-1202-4a25-887c-b44c1369f8cc.png)

**Comment by developeranaz** [comment]
Hi , @mikeje  don't deploy Beta Project its maybe unstable/incomplete.
Deploy this https://github.com/developeranaz/Mega.nz-Rclone-Index-Heroku
